### ISSUE TITLE
[issue] set_local_config and get_local_config force parameter names in lowercase

### ISSUE THREAD

**Issue by pyMatJ** [autolab-project/autolab#5]
When saving a local configuration using the autolab.set_local_config() function, the arguments are written to the local_config.ini file in lowercase regardless of the one in the Driver_<Connection> class.
Same, if the local_config.ini file is set up by hand with the proper case, loading through the GUI passes these parameters in lowercase (and thus the __init__ call fails).

So far the only workaround is to leave all arguments in the Driver_<Connection> class in lowercase.

**Comment by Python-simulation** [comment]
Hi! I fixed this issue in commit [d39bb45](https://github.com/Python-simulation/autolab/commit/d39bb4507c438fbb3b41b09c50579d2da639c07e). Note that the function set_local_config was removed in the most recent version, only setting up the config by hand is possible now.
